sets.exported={
    main={ name="Solstice", augments={'INT+15','"Mag.Atk.Bns."+10','"Refresh"+1',}},
    sub="Genmei Shield",
    range={ name="Dunna", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    head="Ea Hat",
    body="Ea Houppelande",
    hands="Ea Cuffs",
    legs="Ea Slops",
    feet="Geo. Sandals +3",
    neck="Loricate Torque +1",
    waist="Fucho-no-Obi",
    left_ear="Mendi. Earring",
    right_ear="Infused Earring",
    left_ring="Defending Ring",
    right_ring={ name="Dark Ring", augments={'Breath dmg. taken -4%','Phys. dmg. taken -6%',}},
    back="Moonbeam Cape",
}